# MD033 - Inline HTML
# MD033 is disabled to allow inline HTML for custom styling
MD033:
  allowed_elements: ["div", "span", "a", "img", "p", "h1", "h2", "h3"]

# MD041 - First line in file should be a top level heading
# MD041 is disabled to allow files without a top-level heading
MD041: false

# MD013 - Line length
# MD013 is disabled to allow longer lines for code blocks and inline HTML
MD013: false
