#!/bin/bash

set -e

case "$1" in
    configure                                       )

        # Set the theme as the default if it not already set
        if ! grep -q '^GRUB_THEME=' /etc/default/grub; then
            echo 'GRUB_THEME="/usr/share/grub/themes/polka-dots_dark/theme.txt"' >> /etc/default/grub
        else
            # Set the resolution to detect screen resolution
            sed -i 's/^GRUB_GFXMODE=.*/GRUB_GFXMODE="auto"/' /etc/default/grub
            sed -i 's|^GRUB_THEME=.*|GRUB_THEME="/usr/share/grub/themes/polka-dots_dark/theme.txt"|' /etc/default/grub
        fi



    ;;
    abort-upgrade|abort-remove|abort-deconfigure    ) ;;
    *                                               )
        echo "ERROR: postinst called with unknown argument '$1'."
        exit 1
    ;;
esac
