#!/usr/env bash

set -e

case "$1" in
    configure                                       )
        test ! -d /usr/grub || rm -rf /usr/grub
    ;;
    abort-upgrade|abort-remove|abort-deconfigure    ) ;;
    *                                               )
        echo "ERROR: postinst called with unknown argument '$1'."
        exit 1
    ;;
esac
